/**
 * 청춘 기억 저장소 - 주차별 퀴즈 데이터 정의 파일
 * 
 * [데이터 구조 설명]
 * - WEEKLY_QUIZ_DATA는 전체 주차의 퀴즈 데이터들을 담고 있는 2차원 배열입니다.
 * - 각 내부 배열(예: WEEKLY_QUIZ_DATA[0])은 특정 주차의 퀴즈 문제들(객체 형태)을 가지고 있습니다.
 * - 각 문제 객체는 다음 항목으로 구성됩니다:
 *   - category: 문제의 주제나 분류 (예: "기념일", "꽃이름", "역사인물" 등)
 *   - question: 어르신들이 읽으실 퀴즈 질문 내용
 *   - answer: 퀴즈의 정답 텍스트
 *   - hint: 정답을 맞히기 어려우실 때 제공되는 도움말(힌트)
 *   - image: 낱말 퀴즈 등 격자판 이미지가 필요한 경우 매칭될 이미지 파일명 (선택사항)
 */

const WEEKLY_QUIZ_DATA = [
// ==========================================
// 5월 퀴즈 데이터 (인덱스 0 ~ 3)
// ==========================================
[
  // 5월 1주차 (인덱스 0)
  {category:"기념일",question:"5월 8일, 부모님 가슴에 달아드리는 꽃은?",answer:"카네이션",hint:"어버이날의 상징이에요."},
  {category:"꽃이름",question:"5월의 여왕이라 불리는 붉은 꽃은?",answer:"장미",hint:"가시가 있어요."},
  {category:"과거회상",question:"청군백군 나누어 달리던 학교 행사는?",answer:"운동회",hint:"박 터뜨리기도 했지요."},
  {category:"역사인물",question:"한글을 만드신 조선의 임금님은?",answer:"세종대왕",hint:"만원권에 계세요."},
  {category:"사물",question:"바느질할 때 손가락에 끼우는 것은?",answer:"골무",hint:"바늘에 안 찔려요."},
  {category:"동물",question:"아침에 꼬꼬댁 우는 새는?",answer:"닭",hint:"새벽을 알려요."},
  {category:"초성 속담",question:"ㄴ ㄴㄱ ㄱㅇㅈㄷ ㅁㄹㄷ",answer:"낫 놓고 기역자도 모른다",hint:"쉬운 것도 모를 때요."},
  {category:"기념일",question:"방정환 선생님이 만드신 5월 5일은?",answer:"어린이날",hint:"아이들이 가장 좋아하는 날이에요."},
  {category:"꽃이름",question:"봄 담장에 피는 노란 꽃은?",answer:"개나리",hint:"나리나리 노래가 있어요."},
  {category:"과거회상",question:"소풍 때 어머니가 싸주신 도시락은?",answer:"김밥",hint:"달걀이 들어있어요."},
  {category:"사물",question:"국을 떠먹는 도구는?",answer:"숟가락",hint:"젓가락 친구예요."},
  {category:"동물",question:"코가 길고 덩치가 큰 동물은?",answer:"코끼리",hint:"물을 뿜어요."},
  {category:"초성 속담",question:"ㄱㄴ ㅁㅇ ㄱㅇㅇ ㅇㄴ ㅁㅇ ㄱㄷ",answer:"가는 말이 고와야 오는 말이 곱다",hint:"먼저 친절해야 해요."},
  {category:"역사인물",question:"거북선을 만든 바다의 장군은?",answer:"이순신",hint:"임진왜란의 영웅이에요."},
  {category:"사물",question:"더울 때 손으로 부치는 것은?",answer:"부채",hint:"종이로 만들어요."},
  {category:"동물",question:"집 지키며 멍멍 짖는 동물은?",answer:"강아지",hint:"사람의 친구예요."},
  {category:"꽃이름",question:"하얀 종 모양의 향기로운 꽃은?",answer:"은방울꽃",hint:"방울처럼 생겼어요."},
  {category:"과거회상",question:"빨래를 두드리던 나무 방망이는?",answer:"다듬이방망이",hint:"탁탁 소리가 났어요."},
  {category:"사물",question:"머리를 단정히 빗는 촘촘한 빗은?",answer:"참빗",hint:"어머니들이 쓰셨어요."},
  {category:"초성 속담",question:"ㅇㅇ ㅂㄸㅇㅈㄷ ㅁㅇ ㅂㄹ ㅎㄹ",answer:"입은 비뚤어져도 말은 바로 해라",hint:"정직하게 말하세요."},
],
[
  // 5월 2주차 (인덱스 1)
  {category:"기념일",question:"5월 15일, 선생님께 감사하는 날은?",answer:"스승의 날",hint:"카네이션을 달아드려요."},
  {category:"꽃이름",question:"보라색이며 향기가 진한 봄 꽃나무는?",answer:"라일락",hint:"수수꽃다리라고도 해요."},
  {category:"과거회상",question:"소풍 날 수건 돌리며 하는 놀이는?",answer:"수건돌리기",hint:"앉은 사람 뒤에 수건을 놓아요."},
  {category:"역사인물",question:"5만원권의 주인공인 조선 화가는?",answer:"신사임당",hint:"율곡 이이의 어머니예요."},
  {category:"사물",question:"글씨 쓸 때 먹을 가는 돌판은?",answer:"벼루",hint:"붓과 함께 써요."},
  {category:"동물",question:"꾀가 많고 꼬리가 긴 산 동물은?",answer:"여우",hint:"영리하기로 유명해요."},
  {category:"초성 속담",question:"ㅂ ㅇㄴ ㅁㅇ ㅊ ㄹ ㄱㄷ",answer:"발 없는 말이 천 리 간다",hint:"말조심하라는 뜻이에요."},
  {category:"기념일",question:"5월 21일 부부가 하나 된다는 날은?",answer:"부부의 날",hint:"둘이 하나 된다는 뜻이에요."},
  {category:"꽃이름",question:"진달래와 비슷한 5월 산 꽃은?",answer:"철쭉",hint:"먹으면 안 되는 꽃이에요."},
  {category:"과거회상",question:"학교 앞 문방구에서 하던 놀이는?",answer:"뽑기",hint:"당기면 경품이 나왔어요."},
  {category:"사물",question:"비 올 때 머리 위에 쓰는 것은?",answer:"우산",hint:"물이 안 들어와요."},
  {category:"동물",question:"야옹 하고 우는 귀여운 동물은?",answer:"고양이",hint:"쥐를 잡아요."},
  {category:"초성 속담",question:"ㄷㄷㅇ ㅈ ㅂ ㅈㄹㄷ",answer:"도둑이 제 발 저린다",hint:"잘못한 사람이 먼저 불안해요."},
  {category:"역사인물",question:"1000원권의 주인공인 조선 선비는?",answer:"퇴계 이황",hint:"도산서원을 세우셨어요."},
  {category:"사물",question:"옷을 꿰매는 뾰족한 도구는?",answer:"바늘",hint:"실과 짝꿍이에요."},
  {category:"동물",question:"나무 잘 타고 도토리 좋아하는 동물은?",answer:"다람쥐",hint:"볼이 빵빵해요."},
  {category:"꽃이름",question:"봄 들판에 홀씨 날리는 노란 꽃은?",answer:"민들레",hint:"바람에 씨가 날아가요."},
  {category:"과거회상",question:"봄 논에 벼 심는 일은?",answer:"모내기",hint:"허리가 아팠지요."},
  {category:"사물",question:"옛날 여인들 머리에 꽂던 장식품은?",answer:"비녀",hint:"쪽머리를 고정해요."},
  {category:"초성 속담",question:"ㅅ ㅅ ㅂㄹ ㅇㄷㄲㅈ ㄱㄷ",answer:"세 살 버릇 여든까지 간다",hint:"어릴 때부터 잘 배워야 해요."},
],
[
  // 5월 3주차 (인덱스 2)
  {category:"계절",question:"5월은 사계절 중 어느 계절일까요?",answer:"봄",hint:"민들레가 피어요, 아지랑이"},
  {category:"절기",question:"창포물에 머리를 감으면 나쁜 액운도 막아주고 머리결도 좋아진다고 하는 절기는?",answer:"단오절",hint:"강릉에서는 단오굿도 함"},
  {category:"과거회상",question:"학교에서 선생님께 하던 인사는?",answer:"차렷 경례",hint:"수업 시작 전에 했어요."},
  {category:"역사인물",question:"5000원권의 주인공인 대학자는?",answer:"율곡 이이",hint:"신사임당의 아드님이에요."},
  {category:"사물",question:"칠판에 글씨 쓰는 흰 막대기는?",answer:"분필",hint:"손에 하얗게 묻어요."},
  {category:"동물",question:"등에 혹이 있고 사막을 걷는 동물은?",answer:"낙타",hint:"물 없이 오래 살아요."},
  {category:"초성 속담",question:"ㅋㅅㅇㄷ ㅋㄴㄱ ㅍㅅㅇㄷ ㅍㄴㄷ",answer:"콩심은데 콩나고 팥심은데 팥난다",hint:"모든 일은 순리대로 된다는 뜻"},
  {category:"기념일",question:"석가모니 탄생 음력 4월 8일은?",answer:"부처님 오신 날",hint:"연등을 다는 날이에요."},
  {category:"꽃이름",question:"아까시나무 꽃 색깔은?",answer:"흰색",hint:"달콤한 향기가 나요."},
  {category:"과거회상",question:"교실 앞에 있던 글씨 쓰는 판은?",answer:"칠판",hint:"분필로 썼어요."},
  {category:"역사인물",question:"임진왜란 때 우리나라를 구한 사람은 누구일까요?",answer:"이순신",hint:"거북선"},
  {category:"동물",question:"하늘 높이 나는 새의 왕은?",answer:"독수리",hint:"눈이 아주 좋아요."},
  {category:"초성 속담",question:"ㅌㄲ ㅁㅇ ㅌㅅ",answer:"티끌 모아 태산",hint:"조금씩 모으면 커져요."},
  {category:"역사인물",question:"대동여지도를 만든 지리학자는?",answer:"김정호",hint:"우리나라 지도를 그리셨어요."},
  {category:"사물",question:"손목에 차는 시간 보는 것은?",answer:"시계",hint:"째깍째깍 소리가 나요."},
  {category:"음식",question:"녹두를 물에 불려서 맷돌에 갈아 기름을 두른 후 부쳐 먹는 음식은?",answer:"빈대떡",hint:"막걸리 안주"},
  {category:"지리",question:"우리나라에서 가장 높은 산은?",answer:"백두산",hint:"북한에 있어요"},
  {category:"계절",question:"일년 중 봄에 하는 일은 어느 것일까요?\n\n1. 모내기   2. 고구마캐기\n3. 벼베기   4. 보리베기",answer:"1. 모내기",hint:"봄에는 논에 어린 모를 심어요."},
  {category:"사물",question:"옛날 삼베 옷감 짜던 도구는?",answer:"베틀",hint:"발로 밟으며 짰어요."},
  {category:"초성 속담",question:"ㅎㄹㅇㄷ ㅈ ㅁ ㅎㅁ ㅇㄷ",answer:"호랑이도 제 말 하면 온다",hint:"뒷말 조심하세요."},
],
[
  // 5월 4주차 (인덱스 3)
  {category:"기념일",question:"5월 하순 만물이 자라는 절기는?",answer:"소만",hint:"보리가 익어가는 시기예요."},
  {category:"꽃이름",question:"5월 찔레꽃 색깔은?",answer:"흰색",hint:"야생 장미라고도 해요."},
  {category:"과거회상",question:"봄에 논 갈기 위해 소를 이용한 일은?",answer:"쟁기질",hint:"밭을 갈았어요."},
  {category:"역사인물",question:"해상왕이라 불리는 신라의 인물은?",answer:"장보고",hint:"청해진을 설치하셨어요."},
  {category:"사물",question:"봄비 막는 우산의 재료는?",answer:"천",hint:"방수 처리가 되어있어요."},
  {category:"동물",question:"봄 꽃가루 모으는 부지런한 곤충은?",answer:"벌",hint:"꿀을 만들어요."},
  {category:"초성 속담",question:"ㄸ ㅈㄱ ㅎㅇㅊㄱ",answer:"땅 짚고 헤엄치기",hint:"아주 쉬운 일을 말해요."},
  {category:"기념일",question:"어버이날과 어린이날이 모두 있는 달은?",answer:"5월",hint:"가정의 달이라고 해요."},
  {category:"꽃이름",question:"보라색 붓 모양으로 피는 꽃은?",answer:"붓꽃",hint:"아이리스라고도 해요."},
  {category:"과거회상",question:"옛날 방아 찧을 때 쓰던 통은?",answer:"절구",hint:"쿵쿵 소리가 났어요."},
  {category:"사물",question:"옷감을 매끄럽게 다리는 도구는?",answer:"다리미",hint:"뜨겁게 달구어요."},
  {category:"동물",question:"봄 논두렁에서 개굴개굴 우는 동물은?",answer:"개구리",hint:"올챙이가 변했어요."},
  {category:"초성 속담",question:"ㅂㅈㅈㄷ ㅁㄷㅁ ㄴㄷ",answer:"백지장도 맞들면 낫다",hint:"함께하면 쉬워요."},
  {category:"역사인물",question:"조선의 화가 단원이라 불리는 분은?",answer:"김홍도",hint:"씨름도를 그리셨어요."},
  {category:"사물",question:"소 끌 때 코에 꿰는 줄은?",answer:"코뚜레",hint:"농사에 없어선 안 됐어요."},
  {category:"동물",question:"껍질 깨고 봄에 태어나는 것은?",answer:"병아리",hint:"삐약삐약 울어요."},
  {category:"꽃이름",question:"봄 산에서 피는 연분홍 큰 꽃은?",answer:"산철쭉",hint:"산에서 피어요."},
  {category:"과거회상",question:"봄나물 캐러 산으로 가던 일은?",answer:"봄나물 채취",hint:"두릅 참나물을 캤어요."},
  {category:"사물",question:"옛날 물 길어 나르던 나무 통은?",answer:"물동이",hint:"머리에 이고 날랐어요."},
  {category:"초성 속담",question:"ㅇㅁ ㅇ ㄱㄱㄹ",answer:"우물 안 개구리",hint:"넓은 세상을 모르는 거예요."},
],

// ==========================================
// 6월 퀴즈 데이터 (인덱스 4 ~ 7)
// ==========================================
[
  // 6월 1주차 (인덱스 4)
  {category:"기념일",question:"6월 6일, 나라를 위해 돌아가신 분들을 기리는 날은?",answer:"현충일",hint:"조기를 달아 추모해요."},
  {category:"기념일",question:"6월은 무슨 달?",answer:"호국보훈의 달",hint:"나라 지킨 분들께 감사하는 달이에요."},
  {category:"꽃이름",question:"우리나라의 국화로 영원히 피고 또 피는 꽃은?",answer:"무궁화",hint:"태극기에도 그려져 있어요."},
  {category:"꽃이름",question:"6월에 피는 하얗고 향기로운 꽃은?",answer:"치자꽃",hint:"향수 원료로도 써요."},
  {category:"과거회상",question:"6.25 한국전쟁이 일어난 해는?",answer:"1950년",hint:"동족상잔의 아픈 역사예요."},
  {category:"과거회상",question:"전쟁 후 어렵게 살던 피난민들이 모여 살던 곳은?",answer:"판자촌",hint:"임시로 지은 집들이었어요."},
  {category:"역사인물",question:"인천상륙작전을 성공시킨 미국 장군은?",answer:"맥아더",hint:"6.25 전쟁의 전환점이 됐어요."},
  {category:"역사인물",question:"행주산성에서 왜군을 무찌른 장군은?",answer:"권율",hint:"행주대첩의 영웅이에요."},
  {category:"사물",question:"군인들이 머리를 보호하기 위해 쓰는 쇠모자는?",answer:"철모",hint:"전쟁터에서 꼭 필요해요."},
  {category:"사물",question:"평화를 상징하며 하얀 새가 물어오는 나뭇가지는?",answer:"올리브 가지",hint:"비둘기가 물어와요."},
  {category:"동물",question:"평화의 상징인 하얀 새는?",answer:"비둘기",hint:"평화를 상징해요."},
  {category:"동물",question:"6월 논두렁에서 개굴개굴 우는 동물은?",answer:"개구리",hint:"올챙이가 자란 거예요."},
  {category:"초성 속담",question:"ㅅㄱㅇ ㅁㅇㅁ ㅂㄱ ㅅㅇㄹ ㄱㄷ",answer:"사공이 많으면 배가 산으로 간다",hint:"참견이 너무 많으면 일이 안 돼요."},
  {category:"초성 속담",question:"ㄲ ㄷㅅ ㄷ",answer:"꿩 대신 닭",hint:"없으면 비슷한 걸로 써요."},
  {category:"기념일",question:"나라를 위해 목숨을 바친 분들께 감사하는 방법은?",answer:"태극기 달기",hint:"경의를 표해요."},
  {category:"꽃이름",question:"6월 초 들판에 하얗게 피는 클로버 꽃은?",answer:"토끼풀꽃",hint:"네잎클로버가 행운이에요."},
  {category:"과거회상",question:"6.25 전쟁 때 피난 가며 짊어지던 짐은?",answer:"보따리",hint:"소중한 것만 챙겼지요."},
  {category:"사물",question:"적에게 신호를 보내거나 군대를 지휘할 때 부는 악기는?",answer:"나팔",hint:"삐 하고 소리가 나요."},
  {category:"동물",question:"전쟁터에서 기병대가 타던 동물은?",answer:"말",hint:"빠르고 힘이 세요."},
  {category:"초성 속담",question:"ㄱㅈㄴ ㄱ ㅍㅇㄷ",answer:"가재는 게 편이다",hint:"같은 편끼리 서로 도와요."},
],
[
  // 6월 2주차 (인덱스 5)
  {category:"기념일",question:"음력 5월 5일, 창포물에 머리 감는 날은?",answer:"단오",hint:"그네 타기도 했어요."},
  {category:"기념일",question:"단오에 여인들이 즐겨 타던 것은?",answer:"그네",hint:"높이 올라가면 신났지요."},
  {category:"꽃이름",question:"장마철에 파랗게 피는 물을 좋아하는 꽃은?",answer:"수국",hint:"비를 맞으면 더 예뻐요."},
  {category:"꽃이름",question:"6월 논 주변에 피는 보라색 풀은?",answer:"창포",hint:"단오에 머리 감는 풀이에요."},
  {category:"과거회상",question:"장마철에 지붕 아래 처마 끝에서 뚝뚝 떨어지는 투명한 물방울을 무엇이라고 할까요?",answer:"낙숫물 (또는 처마물 / 빗방울)",hint:"처마를 타고 내려와요."},
  {category:"과거회상",question:"조선 시대에 방랑 시인 김삿갓이나 서민들이 비와 햇볕을 피하기 위해 머리에 쓰던, 대나무나 갈대로 엮은 모자는 무엇일까요?",answer:"삿갓",hint:"대나무로 만들었어요."},
  {category:"역사인물",question:"조선 시대 제4대 임금이자, 태종의 셋째 아들로 한글을 창제하신 분은 누구일까요?",answer:"세종대왕",hint:"한글을 만드셨어요."},
  {category:"역사인물",question:"고려를 세운 태조의 이름은?",answer:"왕건",hint:"개성 왕씨의 시조예요."},
  {category:"사물",question:"비가 많이 오는 날, 발이 젖지 않도록 신는 종아리까지 올라오는 고무 신발은 무엇일까요?",answer:"장화",hint:"발이 안 젖어요."},
  {category:"사물",question:"가뭄 끝에 반갑게 내리는 비를 가리켜 우리가 흔히 '이것 비'라고 부릅니다. 아주 귀하고 값진 비를 뜻하는 이 말은 무엇일까요?",answer:"단비 (또는 약비)",hint:"반가운 비를 말해요."},
  {category:"동물",question:"비 온 후 마당에 나오는 긴 벌레는?",answer:"지렁이",hint:"땅을 기름지게 해요."},
  {category:"동물",question:"장마철 물웅덩이에서 올챙이가 자라는 것은?",answer:"개구리",hint:"물 속에서 알을 낳아요."},
  {category:"초성 속담",question:"ㅎㄹㅇㄷ ㅈ ㅁ ㅎㅁ ㅇㄷ",answer:"호랑이도 제 말 하면 온다",hint:"뒷말은 조심해야 해요."},
  {category:"초성 속담",question:"ㅇㅁ ㅇ ㄱㄱㄹ",answer:"우물 안 개구리",hint:"세상 넓은 줄 모르는 거예요."},
  {category:"기념일",question:"24절기 중 하나로, 일 년 중 태양이 가장 높이 뜨고 '낮의 길이'가 가장 긴 날은 무슨 절기일까요?",answer:"하지",hint:"일 년 중 해가 제일 오래 떠 있어요."},
  {category:"꽃이름",question:"6월에 하얀 꽃이 피는 백합 종류는?",answer:"나리꽃",hint:"백합이라고도 해요."},
  {category:"과거회상",question:"비가 너무 많이 내려서 강물이나 하천이 넘쳐 주변 땅과 논밭이 물에 잠기는 자연재해는 무엇일까요?",answer:"홍수 (또는 수해)",hint:"농작물이 피해를 입었어요."},
  {category:"사물",question:"예전에 방 안에서 숯불을 담아 두고 겨울철 난방을 하거나, 찌개나 찌개 거리를 데우고 젖은 옷을 말리기도 했던 놋쇠나 흙으로 만든 그릇은 무엇일까요?",answer:"화로",hint:"숯불로 열을 냈어요."},
  {category:"동물",question:"여름 빗속에도 씩씩하게 우는 개구리 소리는?",answer:"개굴개굴",hint:"합창처럼 들려요."},
  {category:"초성 속담",question:"ㄱㅅ ㄲㅇ ㄴㅇ ㅇㄷ",answer:"고생 끝에 낙이 온다",hint:"참으면 반드시 좋은 날이 와요."},
  {category:"낱말맞추기",question:"노란색 칸에 공통으로 들어갈 네 글자 단어를 맞혀보세요!",answer:"모래사장",hint:"바닷가나 강가에 모래가 넓고 넓게 깔려 있는 곳이에요.",image:"word_puzzle.png"},
],
[
  // 6월 3주차 (인덱스 6)
  {category:"기념일",question:"6월 초 보리를 수확하는 절기는?",answer:"망종",hint:"씨를 뿌리기도 하는 때예요."},
  {category:"수수께끼",question:"아무리 많이 먹어도 절대 배가 부르지 않고, 오히려 배가 부르면 먹을 수 없는 것은 무엇일까요?",answer:"나이",hint:"매년 새해마다 공짜로 먹습니다"},
  {category:"꽃이름",question:"6월 들판이나 논두렁에 붉게 피는, 중국 미인의 이름에서 따온 꽃은?",answer:"양귀비",hint:"역사 속 절세미인 'OOO'의 이름과 똑같은 꽃이에요."},
  {category:"과거회상",question:"옛날에 모내기나 밭일을 하다가 힘들 때, 한 잔씩 마시던 시원하고 탁한 우리 전통 술은 무엇일까요?",answer:"막걸리",hint:"뽀얗고 하얀 술인데, 흔들어서 마셔야 제맛이지요!"},
  {category:"과거회상",question:"더운 여름날, 커다란 나무 아래나 동네 어귀에 평평하게 만들어 놓아 동네 사람들이 모여 쉬던 나무 침상 같은 곳은 어디일까요?",answer:"평상",hint:"커다란 나무 밑에 널찍하게 짜놓은 나무 침대 같은 곳이에요."},
  {category:"구황작물",question:"6월에 수확하는 대표적인 구황작물로, 쪄서 설탕이나 소금을 찍어 먹기도 하고 조림으로도 먹는 땅속의 보물은 무엇일까요?",answer:"감자",hint:"지금 딱 수확할 때죠! 쪄먹으면 포슬포슬하니 맛 좋습니다."},
  {category:"역사인물",question:"조선시대 농사를 장려한 책 농사직설을 편찬한 왕은?",answer:"세종대왕",hint:"백성의 삶을 위해 힘쓰셨어요."},
  {category:"과일",question:"여름철 대표 과일로, 속은 빨갛고 씨가 많으며 한 입 베어 물면 시원한 과즙이 가득한 커다란 과일은 무엇일까요?",answer:"수박",hint:"겉은 초록색 바탕에 검은 줄무늬가 있고, 속은 빨갛습니다."},
  {category:"사물",question:"보리를 베는 데 쓰던 농기구는?",answer:"낫",hint:"쓱쓱 잘라냈지요."},
  {category:"사물",question:"벼를 심기 전 모판에 키우는 어린 벼는?",answer:"모",hint:"줄 맞춰 논에 심어요."},
  {category:"동물",question:"6월 논에서 울어대는 개구리를 잡아먹는 새는?",answer:"백로",hint:"하얗고 긴 다리를 가졌어요."},
  {category:"날씨",question:"여름에 비가 장대처럼 며칠 동안 계속해서 쏟아지는 현상을 무엇이라고 할까요?",answer:"장마",hint:"여름철에 며칠 동안 쉬지 않고 줄기차게 내리는 비를 말해요."},
  {category:"초성 속담",question:"ㄴ ㄴㄱ ㄱㅇㅈㄷ ㅁㄹㄷ",answer:"낫 놓고 기역자도 모른다",hint:"낫 모양이 기역자와 비슷해요."},
  {category:"초성 속담",question:"ㅂ ㅇㄴ ㅁㅇ ㅊ ㄹ ㄱㄷ",answer:"발 없는 말이 천 리 간다",hint:"말은 빨리 퍼지니 조심해요."},
  {category:"기념일",question:"6월 보리 수확 후 농부들이 쉬는 날을 뭐라 할까요?",answer:"농한기",hint:"농사 쉬는 기간이에요."},
  {category:"넌센스",question:"세상에서 가장 뜨거운 과일은 무엇일까요?",answer:"천도복숭아",hint:"날씨가 아주 뜨거울 때 ‘천도’가 넘는다고 하죠? 그 이름이 들어간 복숭아예요!"},
  {category:"과거회상",question:"보리타작 후 키로 알곡을 고르는 일은?",answer:"키질",hint:"쭉정이를 날려보내요."},
  {category:"사물",question:"닦으면 닦을수록 더 더러워지는 것은 무엇일까요?",answer:"걸레",hint:"청소할 때 꼭 쓰는 물건입니다"},
  {category:"동물",question:"6월 밭에서 흙을 가르며 기어가는 벌레는?",answer:"지렁이",hint:"땅을 비옥하게 해요."},
  {category:"초성 속담",question:"ㅅ ㅅ ㅂㄹ ㅇㄷㄲㅈ ㄱㄷ",answer:"세 살 버릇 여든까지 간다",hint:"어릴 때부터 잘 배워야 해요."},
  {category:"낱말맞추기",question:"노란색 칸에 공통으로 들어갈 네 글자 단어를 맞혀보세요!",answer:"아지랑이",hint:"봄날 따뜻한 햇볕을 받아 들판이나 아스팔트 위에서 아른아른 피어오르는 열기는 무엇일까요?",image:"word_puzzle_2.png"},
],
[
  // 6월 4주차 (인덱스 7)
  {category:"기념일",question:"6월 말 여름이 본격적으로 시작되는 절기는?",answer:"하지",hint:"낮이 가장 길어요."},
  {category:"기념일",question:"여름 더위가 시작되는 초복은 몇 월쯤?",answer:"7월 초",hint:"삼복 중 첫 번째예요."},
  {category:"동물",question:"뒷다리가 쑥, 앞다리가 쑥 나온 뒤 꼬리가 꼬물꼬물 없어지면 무엇이 될까요?",answer:"개구리",hint:"올챙이가 자라면 논에서 개골개골 우는 이것이 되요."},
  {category:"꽃이름",question:"옛날에 동네 어귀나 마당가에 심어두면 여름철에 주황색 꽃이 피고, 그 꽃가루를 따서 손톱에 올려놓고 비닐로 묶어 빨갛게 물들이던 추억의 꽃은 무엇일까요?",answer:"봉선화",hint:"첫눈이 올 때까지 손톱에 이 물이 남아있으면 첫사랑이 이뤄진다고 했습니다."},
  {category:"수수께끼",question:"앞에서는 눈물을 펑펑 흘리며 우는데, 뒤에서는 꼬리를 살랑살랑 흔드는 것은 무엇일까요?",answer:"촛불",hint:"어두운 방을 밝혀주며 몸을 태워 촛농(눈물)을 흘리는 물건입니다."},
  {category:"음식",question:"동두천 미군부대에서 흘러나온 햄과 소시지를 넣고 김치와 함께 얼큰하게 끓여내던 이 찌개의 이름은 무엇일까요?",answer:"부대찌개",hint:"군부대 주변에서 시작되었다고 해서 이름에 '부대'가 들어갑니다."},
  {category:"넌센스",question:"세상에서 가장 미안해하는 동물은 무엇일까요?",answer:"오소리",hint:"늘 미안하다고 \"오~ 소리\"를 연신 외치는 동물입니다."},
  {category:"역사인물",question:"조선시대 최고의 의학서인 《동의보감》을 집필하여 백성들의 병을 치료하는 데 큰 공을 세운 의학자는 누구일까요?",answer:"허준",hint:"TV 드라마로도 큰 사랑을 받았던 조선의 명의입니다."},
  {category:"사물",question:"여름에 파리와 모기를 잡는 도구는?",answer:"파리채",hint:"철사 망으로 만들어요."},
  {category:"사물",question:"부채에 빨강, 파랑, 노랑의 삼색 문양이 그려진 우리나라 고유의 둥근 부채는?",answer:"태극선",hint:"우리나라 국기에 그려진 문양이 이 부채에도 예쁘게 그려져 있습니다."},
  {category:"동물",question:"여름 밤 빛을 내며 날아다니는 곤충은?",answer:"반딧불이",hint:"개똥벌레라고도 해요."},
  {category:"과거회상",question:"옛날 여름철, 전기가 귀하던 시절에 대나무를 엮어 사람 크기로 만들어 품고 자면 가슴 사이에 바람이 통해 시원하게 해주던 이 물건은 무엇일까요?",answer:"죽부인",hint:"대나무로 만든 서늘한 여름철 잠자리 단짝입니다."},
  {category:"초성 속담",question:"ㄷㄷㅇ ㅈ ㅂ ㅈㄹㄷ",answer:"도둑이 제 발 저린다",hint:"잘못한 사람이 먼저 드러나요."},
  {category:"초성 속담",question:"ㄱㄴ ㅁㅇ ㄱㅇㅇ ㅇㄴ ㅁㅇ ㄱㄷ",answer:"가는 말이 고와야 오는 말이 곱다",hint:"먼저 잘 대해줘야 해요."},
  {category:"기념일",question:"초여름 밀을 거두는 절기는?",answer:"망종",hint:"보리와 밀을 수확해요."},
  {category:"과거회상",question:"옛날에 단오날이 되면 이 식물을 삶은 물에 머리를 감아 윤기를 내고 더위를 쫓았다고 합니다. 향이 독특한 이 식물은 무엇일까요?",answer:"창포",hint:"머리 결이 비단처럼 고와진다는 단오철 대표 식물입니다."},
  {category:"수수께끼",question:"아무리 많이 때려도 경찰이 절대 잡아가지 않고, 오히려 사람들이 더 세게 때리라고 응원하는 것은 무엇일까요?",answer:"박수",hint:"노래가 끝나거나 신이 날 때 두 손바닥을 마주치는 행동입니다."},
  {category:"음식",question:"소금도 안 넣고 간장도 안 넣었는데, 태어날 때부터 이미 간이 딱 맞아서 짭짤하게 나오는 물고기는 무엇일까요?",answer:"간고등어",hint:"짭조름해서 밥반찬으로 최고인 안동의 대표 생선입니다."},
  {category:"동물",question:"주로 여름철 시골집 마당이나 장독대 근처에 나타나며, 위협을 느끼면 껍질이 벗겨지듯 꼬리를 자르고 도망치는 얼룩덜룩한 파충류는?",answer:"도마뱀",hint:"꼬리가 잘려도 금방 다시 자라나는 미끈한 시골 단골손님입니다."},
  {category:"초성 속담",question:"ㅌㄲ ㅁㅇ ㅌㅅ",answer:"티끌 모아 태산",hint:"조금씩 쌓이면 크게 돼요."},
  {category:"낱말맞추기",question:"노란색 칸에 공통으로 들어갈 네 글자 단어를 맞혀보세요!",answer:"아주머니",hint:"남성이 아닌 성인 여성을 친근하게 부르는 말이자, 보통 결혼한 여성을 일컫는 말은 무엇일까요?",image:"word_puzzle_4.png"},
],

// ==========================================
// 7월 퀴즈 데이터 (인덱스 8 ~ 11)
// ==========================================
[
  // 7월 1주차 (인덱스 8)
  {category:"기념일",question:"7월의 가장 더운 세 날을 묶어 부르는 말은?",answer:"삼복",hint:"초복 중복 말복이에요."},
  {category:"기념일",question:"삼복 중 첫 번째 더운 날은?",answer:"초복",hint:"여름 더위의 시작이에요."},
  {category:"꽃이름",question:"7월 무더위에 연못에서 크게 피는 꽃은?",answer:"연꽃",hint:"심청이가 타고 온 꽃이에요."},
  {category:"꽃이름",question:"뜨거운 여름에도 해를 따라 고개 돌리는 꽃은?",answer:"해바라기",hint:"노란 꽃이 크고 예뻐요."},
  {category:"과거회상",question:"초복에 더위를 이기려 먹던 닭과 인삼 요리는?",answer:"삼계탕",hint:"뜨거운 걸 먹어 더위를 이겼어요."},
  {category:"과거회상",question:"삼복 더위에 냇가에서 발 담그며 더위 식히던 것은?",answer:"탁족",hint:"선비들의 지혜로운 피서법이에요."},
  {category:"역사인물",question:"조선의 실학자로 목민심서를 쓴 분은?",answer:"정약용",hint:"다산이라는 호를 쓰셨어요."},
  {category:"역사인물",question:"임진왜란 때 의병을 일으킨 곽재우 장군의 별명은?",answer:"홍의 장군",hint:"붉은 옷을 입고 싸우셨어요."},
  {category:"사물",question:"여름철 목에 쓱 걸치기도 하고, 땀도 닦고, 찬물에 적셔 열을 식힐 때도 쓰는 직사각형 모양의 무명천은 무엇일까요?",answer:"수건",hint:"목욕탕 갈 때 꼭 챙겨가고, 옛날엔 '이것'으로 세수도 했지요."},
  {category:"사물",question:"시원한 냉면 면발을 가위로 잘라 후루룩 건져 먹을 때, 숟가락과 함께 늘 붙어 다니는 짝꿍은 무엇일까요?",answer:"젓가락",hint:"음식 집어 먹을 때 쓰는 두 가락, 초성은 ㅈㄱㄹ 입니다."},
  {category:"동물",question:"땅속에서 몇 년을 기다렸다가, 여름철 딱 한 철 동안 나무 위에서 \"맴맴~\" 하고 목청껏 노래하는 여름의 전령사는 누구일까요?",answer:"매미",hint:"이름 안에 벌써 울음소리가 숨어있네요! '맴맴' 우는 녀석입니다."},
  {category:"동물",question:"여름 밤 빛을 내며 날아다니는 곤충은?",answer:"반딧불이",hint:"개똥벌레라고도 해요."},
  {category:"초성 속담",question:"ㄱㅅ ㄲㅇ ㄴㅇ ㅇㄷ",answer:"고생 끝에 낙이 온다",hint:"힘든 후엔 반드시 좋은 일이 와요."},
  {category:"초성 속담",question:"ㅂㅈㅈㄷ ㅁㄷㅁ ㄴㄷ",answer:"백지장도 맞들면 낫다",hint:"함께하면 쉬워요."},
  {category:"기념일",question:"우리나라의 가장 바탕이 되는 ‘대한민국 헌법’이 만들어진 날을 기념하는 제헌절은 과연 몇 월 며칠일까요?",answer:"7월 17일",hint:"행운의 숫자 7이 두 번 들어가는 날이에요!"},
  {category:"꽃이름",question:"옛날에 양반집 마당에만 심을 수 있어서 '양반꽃'이라고도 불렸으며, 여름철 담장을 주황색 나팔 모양으로 화사하게 덮는 이 꽃은 무엇일까요?",answer:"능소화",hint:"ㄴㅅㅎ (양반들이 좋아했던 주황색 꽃)"},
  {category:"과일",question:"더운 여름날, 마당에 평상 깔고 앉아 껍질을 '쪼개어' 한 조각씩 들고 베어 먹는, 속이 빨간 여름철 대표 과일은 무엇일까요?",answer:"수박",hint:"줄무늬 옷을 입고 속은 새빨간, 여름에 제일 시원한 과일!"},
  {category:"과거회상",question:"제주도 남자들이 밭일을 하러가거나 일상복으로 입었던 갈색바지를 무엇이라 할까요?",answer:"갈중이",hint:"풋감으로 물 들여서 입어요"},
  {category:"동물",question:"골 논가에서 긴 다리로 유유히 걸어 다니며 개구리나 미꾸라지를 잡아먹는, 온몸이 눈부시게 하얀 새는 무엇일까요?",answer:"백로",hint:"한자로 **'하얀 새'**라는 뜻을 가진 고결한 새입니다."},
  {category:"초성 속담",question:"ㅋ ㅅㅇ ㄷ ㅋ ㄴㄱ ㅍ ㅅㅇ ㄷ ㅍ ㄴㄷ",answer:"콩 심은 데 콩 나고 팥 심은 데 팥 난다",hint:"원인대로 결과가 나와요."},
  {category:"낱말맞추기",question:"노란색 칸에 공통으로 들어갈 네 글자 단어를 맞혀보세요!",answer:"바디워시",hint:"목욕할 때 몸을 깨끗이 씻기 위해 물총처럼 짜서 쓰는 액체 비누를 무엇이라고 할까요?",image:"word_puzzle_3.png"},
],
[
  // 7월 2주차 (인덱스 9)
  {category:"기념일",question:"음력 7월 7일, 견우와 직녀가 만나는 날은?",answer:"칠석",hint:"오작교를 건너 만나요."},
  {category:"기념일",question:"칠석에 까마귀와 까치가 만든 다리는?",answer:"오작교",hint:"하늘에 놓인 다리예요."},
  {category:"꽃이름",question:"여름철 낮에는 꽃봉오리를 오므렸다가 밤이 되면 노란 꽃망울을 수줍게 터뜨리는 꽃은 무엇일까요?",answer:"달맞이꽃",hint:"꽃 이름에 '보름달' 할 때 달이 들어가요."},
  {category:"꽃이름",question:"향이 어찌나 진하고 좋은지, 지나가던 사람도 발길을 멈추게 하는 하얗고 고운 여름 꽃은?",answer:"치자꽃",hint:"열매는 노랗게 천 염색할 때 쓰고, 꽃 이름은 '치'로 시작해요."},
  {category:"과거회상",question:"\"비가 오면 생각나는 그 사람~ 언제나 말이 없던 그 사람~\" 여름 장마철이면 더욱 가슴을 적시는 노래 '그때 그 사람'을 부른 여가수는 누구일까요?",answer:"심수봉",hint:""},
  {category:"과거회상",question:"에어컨도 선풍기도 없던 시절, 대청마루에 앉아 손목을 바삐 움직여 바람을 만들던 손때 묻은 물건은?",answer:"부채",hint:"바람을 일으키는 채, 대나무와 종이로 만들었지요."},
  {category:"역사인물",question:"조선시대 숙종의 사랑을 받았으나 사약을 받고 죽은 왕비는 누구일까요?",answer:"장희빈",hint:"연산군의 어머니"},
  {category:"넌센스",question:"삼계탕에 들어가는 닭들이 가장 무서워하는 '스님'은 누구일까요?",answer:"파계승",hint:"파를 썬다"},
  {category:"사물",question:"귓가에 앵앵거리는 불청객을 쫓으려고 마당에 쑥을 한가득 모아놓고 피우던 연기는 무엇일까요?",answer:"모닥불 / 쑥불 (쑥연기)",hint:"여름밤 마당에서 '이 풀'을 태워 매캐한 연기로 모기를 쫓았지요."},
  {category:"사물",question:"예전 여름에 소 먹이러 갈 때나 밭일할 때 등에 메고 가던 것으로, 거친 풀이나 칡넝쿨을 뜯어 담던 대나무나 싸리로 엮은 가방은 무엇일까요?",answer:"꼴망태 (망태기)",hint:"지게에 얹는 것"},
  {category:"동물",question:"비가 오려 하면 가랑잎 뒤에 숨어 \"뱅덕새 논에 물 넘는다\"며 목청 높여 우는 초록색 미끈이 동물은?",answer:"청개구리",hint:"엄마 말을 참 안 듣고 반대로만 하던 녀석이지요."},
  {category:"동물",question:"한밤중에 동굴에서 나와 밤하늘을 날아다니는, 쥐를 닮았지만 날개가 달린 동물은?",answer:"박쥐",hint:"앞눈이 어둡고 밤에 귀로 들으며 날아다니는, 'O쥐’입니다."},
  {category:"초성 속담",question:"ㅇㅅㄴ ㅇㄴㅁㄷㄹㅇㅅ ㅁㄴㄷ",answer:"원수는 외나무다리에서 만난다",hint:"피하려 해도 결국 만나게 돼요."},
  {category:"초성 속담",question:"ㄴ ㄱㄹㄱ ㅇㅇ",answer:"눈 가리고 아웅",hint:"뻔한 속임수를 말해요."},
  {category:"기념일",question:"견우와 직녀 이야기에서, 은하수 건너편에서 베를 짜며 견우를 그리워하던 별자리의 이름은?",answer:"직녀성",hint:"칠석날 오작교에서 견우를 만나는 그녀의 별 이름이에요."},
  {category:"꽃이름",question:"한낮에는 활짝 피었다가, 밤이 되면 마치 잠을 자듯 꽃잎을 오므리는 연못 위의 하얀 꽃은?",answer:"수련",hint:"이름에 '잠잘 수(睡)' 자가 들어가서 잠자는 연꽃이라고 불러요."},
  {category:"과거회상",question:"한여름 커다란 얼음 덩어리를 대패 같은 기계에 대고 슥슥 갈아서 붉은 딸기 시럽을 뿌려 먹던 이것은?",answer:"빙수 (옛날 팥빙수)",hint:"간 얼음"},
  {category:"사물",question:"방을 어둡게 밝히던 호롱불이나 등잔대에 부어 쓰던, 아주 귀하고 고소한 냄새가 나는 기름은?",answer:"참기름 / 아주까리기름",hint:"나물 무칠 때 넣는 아주 고소한 기름을 옛날엔 불 밝히는 데도 썼답니다."},
  {category:"동물",question:"여름 밤 연못에서 소 울음처럼 크게 우는 커다란 외래종 개구리는?",answer:"황소개구리",hint:"덩치가 엄청나게 크고 목소리가 황소를 닮았어요."},
  {category:"초성 속담",question:"ㄱㄴ ㅁㅇ ㄱㅇㅇ ㅇㄴ ㅁㅇ ㄱㄷ",answer:"가는 말이 고와야 오는 말이 곱다",hint:"친절이 친절을 불러요."},
  {category:"낱말맞추기",question:"노란색 칸에 공통으로 들어갈 네 글자 단어를 맞혀보세요!",answer:"오토바이",hint:"바퀴가 두 개 달린, 엔진을 장착해 빠르게 달릴 수 있는 이륜자동차는 무엇일까요?",image:"word_puzzle_7.png"},
],
[
  // 7월 3주차 (인덱스 10)
  {category:"기념일",question:"더위를 피해 바다나 산으로 떠나는 것은?",answer:"여름휴가",hint:"온 가족이 함께 떠나요."},
  {category:"기념일",question:"7월 중순 가장 더운 중복은?",answer:"중복",hint:"삼복 중 두 번째예요."},
  {category:"꽃이름",question:"바닷가 모래밭에 피는 보라색 꽃은?",answer:"해당화",hint:"동해안에 많이 피어요."},
  {category:"꽃이름",question:"여름 계곡 주변에 피는 분홍색 꽃은?",answer:"봉선화",hint:"손톱에 물들이기도 했어요."},
  {category:"과거회상",question:"여름 방학에 바닷가에서 놀던 기억은?",answer:"해수욕",hint:"모래성도 쌓았지요."},
  {category:"과거회상",question:"계곡에서 물고기를 잡던 놀이는?",answer:"천렵",hint:"고기를 잡아 매운탕을 끓였어요."},
  {category:"역사인물",question:"동해안을 탐험한 조선의 지리학자는?",answer:"김정호",hint:"조선 팔도를 모두 다녔어요."},
  {category:"역사인물",question:"바다를 배경으로 한 소설을 쓴 작가는?",answer:"이순신",hint:"임진록에 바다 전투가 많아요."},
  {category:"사물",question:"바다에서 물에 빠지지 않게 쓰는 것은?",answer:"튜브",hint:"동그란 고무 튜브예요."},
  {category:"사물",question:"모래사장에서 발을 보호하는 신발은?",answer:"샌들",hint:"여름 필수품이에요."},
  {category:"동물",question:"바다에서 사는 가장 큰 동물은?",answer:"고래",hint:"물을 뿜어 올려요."},
  {category:"동물",question:"계곡 돌 밑에 사는 민물고기는?",answer:"꺽지",hint:"낚시로 잡기도 해요."},
  {category:"초성 속담",question:"ㄴ ㄴㄱ ㄱㅇㅈㄷ ㅁㄹㄷ",answer:"낫 놓고 기역자도 모른다",hint:"쉬운 것도 모르는 상황이에요."},
  {category:"초성 속담",question:"ㅂ ㅇㄴ ㅁㅇ ㅊ ㄹ ㄱㄷ",answer:"발 없는 말이 천 리 간다",hint:"말은 빨리 퍼지니 조심해요."},
  {category:"기념일",question:"여름 방학에 아이들이 가장 좋아하는 것은?",answer:"수영",hint:"물놀이가 최고예요."},
  {category:"꽃이름",question:"여름 바다 모래밭에 핀 노란 꽃은?",answer:"달맞이꽃",hint:"밤에 더 밝게 피어요."},
  {category:"과거회상",question:"여름에 멱을 감던 동네 개울은?",answer:"냇가",hint:"친구들과 첨벙첨벙 놀았어요."},
  {category:"사물",question:"여름 해변에서 눈을 보호하는 것은?",answer:"선글라스",hint:"자외선을 막아줘요."},
  {category:"동물",question:"여름 바닷가에서 모래를 파는 집게 달린 동물은?",answer:"게",hint:"옆으로 걸어요."},
  {category:"초성 속담",question:"ㅅ ㅇㄱ ㅇㅇㄱ ㄱㅊㄷ",answer:"소 잃고 외양간 고친다",hint:"미리미리 준비해야 해요."},
  {category:"낱말맞추기",question:"노란색 칸에 공통으로 들어갈 네 글자 단어를 맞혀보세요!",answer:"소상공인",hint:"소기업 중에서도 특히 규모가 작은 소상업인, 자영업자, 수공업자 등을 아울러 이르는 말은 무엇일까요?",image:"word_puzzle_6.png"},
],
[
  // 7월 4주차 (인덱스 11)
  {category:"기념일",question:"7월 말 무더위가 끝나기 전 마지막 복날은?",answer:"말복",hint:"삼복 중 마지막이에요."},
  {category:"기념일",question:"여름 제철 수박을 먹으며 더위를 식히는 때는?",answer:"한여름",hint:"7월 8월이 제일 달아요."},
  {category:"꽃이름",question:"수박 덩굴에 피는 노란 꽃은?",answer:"수박꽃",hint:"작고 노란 꽃이에요."},
  {category:"꽃이름",question:"옥수수 꼭대기에 피는 수염 같은 꽃은?",answer:"옥수수 수꽃",hint:"길고 가늘어요."},
  {category:"과거회상",question:"여름에 우물에 넣어 식힌 후 먹던 과일은?",answer:"수박",hint:"초록 줄무늬가 있어요."},
  {category:"과거회상",question:"옥수수를 삶아 먹으며 여름 간식으로 즐기던 것은?",answer:"삶은 옥수수",hint:"알이 꽉 차서 맛있었어요."},
  {category:"역사인물",question:"수박을 처음 우리나라에 들여온 시대는?",answer:"고려 시대",hint:"몽골에서 들어왔다고 해요."},
  {category:"역사인물",question:"조선시대 농사를 장려한 왕은?",answer:"세종대왕",hint:"백성을 위해 힘쓰셨어요."},
  {category:"사물",question:"수박을 자를 때 쓰는 큰 칼은?",answer:"식칼",hint:"시원하게 반을 갈라요."},
  {category:"사물",question:"수박을 떠먹는 큰 숟가락은?",answer:"국자",hint:"빨간 속살을 퍼요."},
  {category:"동물",question:"여름 수박밭을 지키는 동물은?",answer:"허수아비",hint:"새를 쫓아요."},
  {category:"동물",question:"여름에 수박을 쪼아 먹으려는 새는?",answer:"까치",hint:"흑백 무늬가 있어요."},
  {category:"초성 속담",question:"ㄷㄷㅇ ㅈ ㅂ ㅈㄹㄷ",answer:"도둑이 제 발 저린다",hint:"잘못한 사람은 스스로 드러나요."},
  {category:"초성 속담",question:"ㅅ ㅅ ㅂㄹ ㅇㄷㄲㅈ ㄱㄷ",answer:"세 살 버릇 여든까지 간다",hint:"좋은 습관을 일찍 들여야 해요."},
  {category:"기념일",question:"여름 더위가 절정인 대서는?",answer:"7월 23일경",hint:"일 년 중 가장 더운 때예요."},
  {category:"꽃이름",question:"참외 덩굴에 피는 노란 꽃은?",answer:"참외꽃",hint:"작고 귀여운 꽃이에요."},
  {category:"과거회상",question:"여름 더위에 먹던 팥빙수는?",answer:"팥빙수",hint:"얼음 위에 팥을 얹어요."},
  {category:"사물",question:"여름 과일 껍질을 깎는 도구는?",answer:"과일 칼",hint:"얇게 깎아내요."},
  {category:"동물",question:"수박씨를 먹으러 오는 참새는?",answer:"참새",hint:"짹짹 우는 작은 새예요."},
  {category:"초성 속담",question:"ㅎㄹㅇㄷ ㅈ ㅁ ㅎㅁ ㅇㄷ",answer:"호랑이도 제 말 하면 온다",hint:"없는 사람 얘기하면 나타나요."},
  {category:"낱말맞추기",question:"노란색 칸에 공통으로 들어갈 네 글자 단어를 맞혀보세요!",answer:"배구선수",hint:"배구 네트를 사이에 두고 공을 쳐서 상대방 진영으로 넘기는 구기 운동의 전문 선수를 말해요.",image:"word_puzzle_5.png"},
]
];